version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app_network

  api:
    build: ./app
    ports:
      - "8000:3000"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
