name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd cd frontend/container-app && npm install
          cd ../app && npm install

      - name: Run Tests
        run: |
          cd cd frontend/container-app && npm test
          cd ../app && npm test

      - name: Lint Code
        run: |
          cd frontend/container-app && npm run lint
          cd ../app && npm run lint

